#!/usr/bin/env python3
"""gen_tables.py - lookup tables for the KeySynth kernel (offline, no pedal).

The kernel may not divide and has no math library, so everything that needs
exp/pow is precomputed here and shipped through the manifest's const_blob.

Writes (paths relative to the project root):
  effects/keysynth/ks_tables.bin   float32 little-endian words -> const_blob.init
  effects/keysynth/ks_tables.h     word offsets of each table (kernel + harness)
  host/ks_tables.inc               the same words as C initializers (harness)
  host/ks_manifest.h               knob ranges/defaults from manifest.json (harness)

Usage (from the project root):
  stomphacks/.venv/bin/python3 tools-local/gen_tables.py           # write
  stomphacks/.venv/bin/python3 tools-local/gen_tables.py --check   # verify only
"""

import json
import math
import struct
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
EFFECT = ROOT / "effects" / "keysynth"
HOST = ROOT / "host"

FS = 44100.0
BLOCK = 16                 # frames per audio call

N_NOTES = 128              # MIDI 0..127
N_SEMI = 49                # Pitch knob 0..48 = -24..+24 semitones
N_STEPS = 101              # knobs 0..100

# Attack/Release knob -> time constant: 1 ms at 0, 3 s at 100, exponential.
ENV_TAU_MIN, ENV_TAU_MAX = 0.001, 3.0
# Rate knob -> LFO frequency: 0.1 Hz at 0, 20 Hz at 100, exponential.
LFO_HZ_MIN, LFO_HZ_MAX = 0.1, 20.0
# Glide knob -> time constant of the pitch slide: 0 = no glide (the pitch
# lands within one block), 1..100 = 20 ms .. 0.7 s, exponential. A slide
# sounds finished after about three time constants: 60 ms .. 2.1 s.
GLD_TAU_MIN, GLD_TAU_MAX = 0.020, 0.7


def f32(x):
    return struct.unpack("<f", struct.pack("<f", x))[0]


def build():
    """Return [(name, [floats])] in file order."""
    freq = [440.0 * 2.0 ** ((n - 69) / 12.0) for n in range(N_NOTES)]
    inc = [f / FS for f in freq]                     # phase increment per sample
    rinc = [FS / f for f in freq]                    # its reciprocal (PolyBLEP)
    semi = [2.0 ** ((i - 24) / 12.0) for i in range(N_SEMI)]
    env = []
    for k in range(N_STEPS):
        tau = ENV_TAU_MIN * (ENV_TAU_MAX / ENV_TAU_MIN) ** (k / 100.0)
        env.append(1.0 - math.exp(-BLOCK / (tau * FS)))   # one-pole, per BLOCK
    lfo = []
    for k in range(N_STEPS):
        hz = LFO_HZ_MIN * (LFO_HZ_MAX / LFO_HZ_MIN) ** (k / 100.0)
        lfo.append(hz * BLOCK / FS)                  # phase increment per BLOCK
    gld = [1.0]
    for k in range(1, N_STEPS):
        tau = GLD_TAU_MIN * (GLD_TAU_MAX / GLD_TAU_MIN) ** ((k - 1) / 99.0)
        gld.append(1.0 - math.exp(-BLOCK / (tau * FS)))   # one-pole, per BLOCK
    return [("INC", inc), ("RINC", rinc), ("SEMI", semi),
            ("ENV", env), ("LFO", lfo), ("GLD", gld)]


def render():
    tables = build()
    words, offsets = [], []
    for name, vals in tables:
        offsets.append((name, len(words), len(vals)))
        words.extend(vals)
    blob = struct.pack("<%df" % len(words), *words)

    h = ["/* generated by tools-local/gen_tables.py; do not edit. */",
         "#ifndef KS_TABLES_H", "#define KS_TABLES_H", "",
         "/* word offsets into KS_TAB (float32 words, const_blob) */"]
    for name, off, n in offsets:
        h.append("#define KS_TAB_%-5s %4d   /* %d words */" % (name, off, n))
    h += ["#define KS_TAB_WORDS %4d" % len(words), "",
          "#define KS_N_NOTES   %d" % N_NOTES,
          "#define KS_N_SEMI    %d" % N_SEMI,
          "#define KS_N_STEPS   %d" % N_STEPS, "",
          "#endif /* KS_TABLES_H */", ""]

    raw = struct.unpack("<%dI" % len(words), blob)
    inc_lines = ["/* generated by tools-local/gen_tables.py; do not edit. */"]
    for i in range(0, len(raw), 6):
        inc_lines.append(", ".join("0x%08xu" % w for w in raw[i:i + 6]) + ",")
    inc_txt = "\n".join(inc_lines) + "\n"

    man = json.loads((EFFECT / "manifest.json").read_text())
    mh = ["/* generated by tools-local/gen_tables.py from manifest.json;",
          " * do not edit. Knob ranges for the desktop harness. */",
          "#ifndef KS_MANIFEST_H", "#define KS_MANIFEST_H", "",
          "#define KS_STATE_BYTES_MANIFEST %d" % man["state_bytes"],
          "#define KS_NUM_KNOBS %d" % len(man["params"]),
          "static const struct { const char *name; int max; int def; int vol; } "
          "KS_KNOBS[KS_NUM_KNOBS] = {"]
    for p in man["params"]:
        mx = p["max"] if "max" in p else len(p["values"]) - 1
        mh.append('    { "%s", %d, %d, %d },' % (
            p["name"], mx, p["default"], 1 if p.get("curve") == "stock_vol" else 0))
    mh += ["};", "", "#endif /* KS_MANIFEST_H */", ""]

    return {
        EFFECT / "ks_tables.bin": blob,
        EFFECT / "ks_tables.h": "\n".join(h).encode(),
        HOST / "ks_tables.inc": inc_txt.encode(),
        HOST / "ks_manifest.h": "\n".join(mh).encode(),
    }, len(words)


def main():
    check = "--check" in sys.argv[1:]
    files, nwords = render()
    bad = 0
    for path, data in files.items():
        if check:
            if not path.is_file() or path.read_bytes() != data:
                print("STALE  %s" % path.relative_to(ROOT))
                bad += 1
            else:
                print("ok     %s" % path.relative_to(ROOT))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
            print("wrote  %s (%d B)" % (path.relative_to(ROOT), len(data)))
    print("%d table words (const_blob.words must be %d)" % (nwords, nwords))
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
