/* effects/keysynth/keysynth.c - a two-oscillator mono synth voice.
 *
 * The voice is played by parameter writes: the Key knob is gate and pitch.
 * 0 = gate off; n = (n-1) x 10 cents above C0 (MIDI note 12). The keyboard
 * controller writes the note and the pitch bend as this one number, so a
 * note-on can never be separated from its pitch. The input passes through
 * unchanged and the synth is added on both channels:
 *
 *     out = dry + fade * synth        (fade = the firmware bypass crossfade)
 *
 * Pitch moves in three ways. A note after a gap starts on pitch. A move of
 * the Key knob by less than a semitone is a bend and is smoothed over about
 * 20 ms, so the 10-cent steps do not show. A larger move while the gate is
 * open is a tied note: with Glide at 0 it lands at once, otherwise the pitch
 * slides there.
 *
 * Structure: everything slow (knob decode, envelope, LFO, pitch, smoothing)
 * runs once per 16-frame block. The oscillators run per sample, and each
 * oscillator's gain is a straight line from the gain the last block ended on
 * to this block's target, so no control change can step the output.
 *
 * Kernel contract (stomphacks docs/building-effects.md): guard prologue,
 * every coefficient read once into a local and range-checked, every bus write
 * clamped, no calls, no divides, no stdlib, no statics, no stack.
 * State budget: see keysynth_state.h (84 of 188 bytes).
 *
 * The skeleton (guard prologue, coefficient discipline, output clamp) is
 * stomphacks effects/gain/gain.c:
 * Copyright (c) 2026 Thomas Hammer (Waveformer). MIT license.
 * The synth voice was added for the MS-Plus-Synth project. MIT license.
 */

#include <stdint.h>
#include "sh_params.h"       /* generated into build/ from manifest.json */
#include "ks_tables.h"       /* generated by tools-local/gen_tables.py */
#include "keysynth_state.h"

#if SH_STATE_BYTES != KS_STATE_BYTES
#error "manifest state_bytes and keysynth_state.h disagree"
#endif

/* lookup tables, shipped through the manifest's const_blob (float32 words) */
extern const uint32_t KS_TAB[];

/* knob maxima; these must match manifest.json (host/run_tests.sh checks) */
#define KS_MAX_KEY    1000
#define KS_MAX_WAVE1     3
#define KS_MAX_WAVE2     4
#define KS_MAX_PITCH    48
#define KS_MAX_STEP    100
#define KS_MAX_LFO     100
#define KS_LFO_OFF      50          /* LFO knob: below = vibrato, above = tremolo */
#define KS_LFO_STEP    0.02f        /* one click of the LFO knob, as a share of the full depth */

#define KS_PIT_BASE    12.0f        /* Key 1 is MIDI note 12 (C0) */
#define KS_PIT_STEP    0.1f         /* one Key click is 10 cents */
#define KS_PIT_MIN     12.0f
#define KS_PIT_MAX     112.0f       /* Key 1000 is note 111.9 */
#define KS_SEMI_EXP    0.05776227f  /* ln(2)/12: one semitone as an exponent */
#define KS_BEND_SPAN   0.95f        /* Key moves up to here (semitones) are a bend */
#define KS_BEND_SMOOTH 0.018f       /* per-block one-pole for a bend, tau ~= 20 ms */
#define KS_GLIDE_DONE  0.05f        /* a slide is over within 5 cents of its target */

#define KS_AMP         0.25f        /* one oscillator's peak at Level 80 */
#define KS_SMOOTH      0.0324f      /* per-block one-pole, tau ~= 11 ms */
#define KS_ENV_FLOOR   1.0e-4f      /* release below -80 dB snaps to zero */
#define KS_CENT50      0.02888113f  /* ln(2)/12 * 0.5: 50 cents as an exponent */
#define KS_INC_MAX     0.45f        /* keep oscillators below Nyquist */
#define KS_RINC_MIN    2.2222222f   /* 1 / KS_INC_MAX */
#define KS_INV_FRAMES  0.0625f      /* 1 / SH_FRAMES */
#define KS_SYNTH_LIMIT 2.0f         /* honest synth peak is about 0.45 */
#define KS_COEF_MAX    1.01f        /* knob/max is 0..1; allow rounding */

/* knob coefficient (knob/max as float) -> integer click, 0..max */
#define KS_CLICK(dst, c, max) do {                                     \
        (dst) = (int)((c) * (float)(max) + 0.5f);                      \
        if ((dst) > (max)) (dst) = (max);                              \
    } while (0)

/* sin(2*pi*p) for p in 0..1: a parabola with one refinement step,
 * max error about 0.1 %. No table, no stdlib. */
#define KS_SIN01(dst, p) do {                                          \
        float x_ = 1.0f - (p) - (p);                                   \
        float ax_ = (x_ < 0.0f) ? -x_ : x_;                            \
        float y_ = 4.0f * x_ * (1.0f - ax_);                           \
        float ay_ = (y_ < 0.0f) ? -y_ : y_;                            \
        (dst) = y_ + 0.225f * (y_ * ay_ - y_);                         \
    } while (0)

/* PolyBLEP residual of a unit step at phase 0, scaled by sgn and added to v.
 * t = phase 0..1, dt = phase increment, rdt = 1/dt (from the table). */
#define KS_BLEP(v, sgn, t, dt, rdt) do {                               \
        if ((t) < (dt)) {                                              \
            float x_ = (t) * (rdt);                                    \
            (v) += (sgn) * (x_ + x_ - x_ * x_ - 1.0f);                 \
        } else if ((t) > 1.0f - (dt)) {                                \
            float x_ = ((t) - 1.0f) * (rdt);                           \
            (v) += (sgn) * (x_ * x_ + x_ + x_ + 1.0f);                 \
        }                                                              \
    } while (0)

/* advance the phase by one sample */
#define KS_STEP(p, inc) do {                                           \
        (p) += (inc);                                                  \
        if ((p) >= 1.0f) (p) -= 1.0f;                                  \
    } while (0)

/* ramp the gain one sample and add the oscillator sample to both channels.
 * The synth sample is clamped before it is added so that a bad synth value
 * can never take the dry signal down with it; the sum is clamped again
 * because every bus write is. NaN fails any comparison. */
#define KS_EMIT(i, v) do {                                             \
        float s_, a_, b_;                                              \
        g += dg;                                                       \
        s_ = (v) * g;                                                  \
        if (!(s_ > -KS_SYNTH_LIMIT && s_ < KS_SYNTH_LIMIT)) s_ = 0.0f; \
        a_ = eff[(i)] + s_;                                            \
        b_ = eff[(i) + SH_CH_B_OFFSET] + s_;                           \
        if (!(a_ > -8.0f && a_ < 8.0f)) a_ = 0.0f;                     \
        if (!(b_ > -8.0f && b_ < 8.0f)) b_ = 0.0f;                     \
        eff[(i)]                  = a_;                                \
        eff[(i) + SH_CH_B_OFFSET] = b_;                                \
    } while (0)

void SH_AUDIO_FN(void **instance, void **ctx)
{
    const float *coef = (const float *)instance[1];
    float *restrict eff = (float *)ctx[1];
    ks_state_t *st    = (ks_state_t *)instance[2];
    const float *tab  = (const float *)KS_TAB;
    int i, o;

    /* ---- mandatory guard prologue --------------------------------------
     * The firmware can run this function against an instance whose init has
     * not run yet (the effect browser live-previews every effect). Check
     * first, and if anything is not sane, write SILENCE.
     *
     * Every coefficient is read ONCE into a local here. The firmware can
     * rewrite coefficient memory while a block runs, so nothing below this
     * point reads coef[] again.
     */
    unsigned ok = 1;
#ifdef SH_STATE_GUARD
    if (((const uint32_t *)instance[2])[SH_STATE_GUARD_WORD]
            != SH_STATE_GUARD)
        ok = 0;                 /* init has not run yet */
#endif
    float fade   = coef[SH_COEFF_BYPASS];   /* 0 = bypassed, 1 = active */
    float cKey   = coef[SH_PARAM_KEY];
    float tLevel = coef[SH_PARAM_LEVEL];    /* the curved amplitude, 0..1.5 */
    float cWave1 = coef[SH_PARAM_WAVE1];
    float cWave2 = coef[SH_PARAM_WAVE2];
    float cPitch = coef[SH_PARAM_PITCH];
    float cDet   = coef[SH_PARAM_DTUNE];
    float tMix   = coef[SH_PARAM_MIX];
    float cGlide = coef[SH_PARAM_GLIDE];
    float cAtk   = coef[SH_PARAM_ATK];
    float cRel   = coef[SH_PARAM_REL];
    float cLfo   = coef[SH_PARAM_LFO];
    float cRate  = coef[SH_PARAM_RATE];

    if (!(fade   >= 0.0f && fade   <= 1.0f))        ok = 0;
    if (!(tLevel >= 0.0f && tLevel <= 1.6f))        ok = 0;
    if (!(cKey   >= 0.0f && cKey   <= KS_COEF_MAX)) ok = 0;
    if (!(cWave1 >= 0.0f && cWave1 <= KS_COEF_MAX)) ok = 0;
    if (!(cWave2 >= 0.0f && cWave2 <= KS_COEF_MAX)) ok = 0;
    if (!(cPitch >= 0.0f && cPitch <= KS_COEF_MAX)) ok = 0;
    if (!(cDet   >= 0.0f && cDet   <= KS_COEF_MAX)) ok = 0;
    if (!(tMix   >= 0.0f && tMix   <= KS_COEF_MAX)) ok = 0;
    if (!(cGlide >= 0.0f && cGlide <= KS_COEF_MAX)) ok = 0;
    if (!(cAtk   >= 0.0f && cAtk   <= KS_COEF_MAX)) ok = 0;
    if (!(cRel   >= 0.0f && cRel   <= KS_COEF_MAX)) ok = 0;
    if (!(cLfo   >= 0.0f && cLfo   <= KS_COEF_MAX)) ok = 0;
    if (!(cRate  >= 0.0f && cRate  <= KS_COEF_MAX)) ok = 0;

    if (!ok) {
        for (i = 0; i < SH_FRAMES; i++) {
            eff[i]                  = 0.0f;
            eff[i + SH_CH_B_OFFSET] = 0.0f;
        }
        return;
    }

    /* ---- knob decode ---------------------------------------------------- */
    int key, wave1, wave2, pitch2, iglide, iatk, irel, lfo, irate;
    KS_CLICK(key,    cKey,   KS_MAX_KEY);
    KS_CLICK(wave1,  cWave1, KS_MAX_WAVE1);
    KS_CLICK(wave2,  cWave2, KS_MAX_WAVE2);
    KS_CLICK(pitch2, cPitch, KS_MAX_PITCH);
    KS_CLICK(iglide, cGlide, KS_MAX_STEP);
    KS_CLICK(iatk,   cAtk,   KS_MAX_STEP);
    KS_CLICK(irel,   cRel,   KS_MAX_STEP);
    KS_CLICK(lfo,    cLfo,   KS_MAX_LFO);
    KS_CLICK(irate,  cRate,  KS_MAX_STEP);

    /* ---- state in, scrubbed ---------------------------------------------
     * Init zeroes the state, so this only matters if something went wrong.
     * A NaN parked in the state must not be able to mute the voice for good.
     */
    float env    = st->env;
    float sLevel = st->sLevel;
    float sMix   = st->sMix;
    float sVib   = st->sVib;
    float sTrem  = st->sTrem;
    float lph    = st->lph;
    float pit    = st->pit;
    float ptp    = st->ptp;
    int   flags  = st->flags & (KS_FLAG_GATE | KS_FLAG_GLIDE);
    if (!(env    >= 0.0f && env    <= 1.0f)) env    = 0.0f;
    if (!(sLevel >= 0.0f && sLevel <= 1.6f)) sLevel = 0.0f;
    if (!(sMix   >= 0.0f && sMix   <= 1.0f)) sMix   = 0.0f;
    if (!(sVib   >= 0.0f && sVib   <= 1.0f)) sVib   = 0.0f;
    if (!(sTrem  >= 0.0f && sTrem  <= 1.0f)) sTrem  = 0.0f;
    if (!(lph    >= 0.0f && lph    <  1.0f)) lph    = 0.0f;
    if (!(pit >= KS_PIT_MIN && pit <= KS_PIT_MAX)) pit = KS_PIT_MIN;
    if (!(ptp >= KS_PIT_MIN && ptp <= KS_PIT_MAX)) ptp = KS_PIT_MIN;

    /* ---- gate, pitch and envelope (per block) ---------------------------
     * 0 -> n   gate opens on pitch, the attack runs from wherever the
     *          envelope is
     * n -> m   tied: the envelope keeps running. A move below a semitone is
     *          a bend; a larger one is a new note, which starts a slide
     *          (Glide 0: the table holds 1.0, so the slide lands at once)
     * n -> 0   release; the last pitch keeps sounding while it fades
     */
    if (key > 0) {
        float tp = KS_PIT_BASE + (float)(key - 1) * KS_PIT_STEP;
        if (!(flags & KS_FLAG_GATE)) {
            pit   = tp;
            flags = KS_FLAG_GATE;
        } else {
            float d = tp - ptp;
            if (d < 0.0f) d = -d;
            if (d > KS_BEND_SPAN) flags |= KS_FLAG_GLIDE;
            d = tp - pit;
            if (flags & KS_FLAG_GLIDE) {
                pit += tab[KS_TAB_GLD + iglide] * d;
                d = tp - pit;
                if (d < 0.0f) d = -d;
                if (d < KS_GLIDE_DONE) flags = KS_FLAG_GATE;
            } else {
                pit += KS_BEND_SMOOTH * d;
            }
        }
        if (pit < KS_PIT_MIN) pit = KS_PIT_MIN;
        if (pit > KS_PIT_MAX) pit = KS_PIT_MAX;
        ptp = tp;
        env += tab[KS_TAB_ENV + iatk] * (1.0f - env);
    } else {
        flags = 0;
        env -= tab[KS_TAB_ENV + irel] * env;
        if (env < KS_ENV_FLOOR) env = 0.0f;
    }

    /* ---- smoothing of the continuous knobs (per block) ------------------
     * Wave2 Off is the mix going to zero, so switching oscillator 2 on or
     * off fades like any other mix change.
     */
    float tVib = 0.0f, tTrem = 0.0f;
    if (lfo < KS_LFO_OFF) tVib  = (float)(KS_LFO_OFF - lfo) * KS_LFO_STEP;
    else                  tTrem = (float)(lfo - KS_LFO_OFF) * KS_LFO_STEP;
    if (tMix   > 1.0f) tMix   = 1.0f;
    if (tVib   > 1.0f) tVib   = 1.0f;
    if (tTrem  > 1.0f) tTrem  = 1.0f;
    if (wave2 == 0)    tMix   = 0.0f;
    sLevel += KS_SMOOTH * (tLevel - sLevel);
    sMix   += KS_SMOOTH * (tMix   - sMix);
    sVib   += KS_SMOOTH * (tVib   - sVib);
    sTrem  += KS_SMOOTH * (tTrem  - sTrem);

    /* ---- LFO (per block): tremolo on the level, vibrato on the pitch ----
     * Both depths are smoothed and both are always applied, so turning the
     * LFO knob from vibrato through Off into tremolo crossfades.
     */
    float lfov, trem, vib;
    lph += tab[KS_TAB_LFO + irate];
    if (lph >= 1.0f) lph -= 1.0f;
    KS_SIN01(lfov, lph);
    trem = 1.0f - sTrem * (0.5f - 0.5f * lfov);        /* 1 .. 1-depth */
    vib  = sVib * lfov * KS_SEMI_EXP;                  /* +/-100 cents max */

    /* ---- pitch (per block) ----------------------------------------------
     * The nearest whole note comes from the table. What is left of the
     * pitch (at most half a semitone), the vibrato and the detune are one
     * small exponent e, which scales the increment by exp(e) ~= 1 + e + e*e/2
     * and the reciprocal by exp(-e). Without vibrato |e| stays below 0.06 and
     * the error under a tenth of a cent; at the peak of the deepest vibrato
     * |e| reaches 0.12 and the error half a cent. Oscillator 2's semitones
     * come from a second table; read backwards it is the reciprocal.
     */
    int   note  = (int)(pit + 0.5f);
    float binc  = tab[KS_TAB_INC  + note];
    float brinc = tab[KS_TAB_RINC + note];
    float e1    = (pit - (float)note) * KS_SEMI_EXP + vib;
    float e2    = e1 + cDet * KS_CENT50;               /* Dtune: 0..+50 cents */
    float q1    = 0.5f * e1 * e1;
    float q2    = 0.5f * e2 * e2;
    float inc1  = binc  * (1.0f + e1 + q1);
    float rinc1 = brinc * (1.0f - e1 + q1);
    float inc2  = binc  * tab[KS_TAB_SEMI + pitch2] * (1.0f + e2 + q2);
    float rinc2 = brinc * tab[KS_TAB_SEMI + KS_MAX_PITCH - pitch2]
                        * (1.0f - e2 + q2);
    if (inc1 > KS_INC_MAX) { inc1 = KS_INC_MAX; rinc1 = KS_RINC_MIN; }
    if (inc2 > KS_INC_MAX) { inc2 = KS_INC_MAX; rinc2 = KS_RINC_MIN; }

    /* ---- gain targets for this block ------------------------------------ */
    float amp = fade * sLevel * env * trem * KS_AMP;

    /* ---- hand the block's values to the oscillator passes ---------------
     * Through the state area, not through locals: the kernel has no stack,
     * and holding both oscillators' values in registers across the sample
     * loops is more than the caller-saved registers can carry.
     */
    st->osc[0].inc  = inc1;
    st->osc[0].rinc = rinc1;
    st->osc[0].tg   = amp * (1.0f - sMix);
    st->osc[0].wave = wave1;
    st->osc[1].inc  = inc2;
    st->osc[1].rinc = rinc2;
    st->osc[1].tg   = amp * sMix;
    st->osc[1].wave = wave2 - 1;  /* Off (-1): the fade-out runs as a sine */
    st->env    = env;
    st->sLevel = sLevel;
    st->sMix   = sMix;
    st->sVib   = sVib;
    st->sTrem  = sTrem;
    st->lph    = lph;
    st->pit    = pit;
    st->ptp    = ptp;
    st->flags  = flags;

    /* ---- the two oscillators --------------------------------------------
     * One pass per oscillator, each adding into the bus. A silent oscillator
     * is skipped (the bus is then not written at all) but its phase still
     * advances, so the two stay in a fixed relation.
     */
    for (o = 0; o < 2; o++) {
        ks_osc_t *os = &st->osc[o];
        float p    = os->ph;
        float g    = os->g;
        float inc  = os->inc;
        float rinc = os->rinc;
        float tg   = os->tg;
        float dg;
        int   wave = os->wave;
        if (!(p >= 0.0f && p <  1.0f)) p = 0.0f;
        if (!(g >= 0.0f && g <= 1.0f)) g = 0.0f;

        if (g > 0.0f || tg > 0.0f) {
            dg = (tg - g) * KS_INV_FRAMES;
            if (wave == 0) {                            /* saw */
                for (i = 0; i < SH_FRAMES; i++) {
                    float v;
                    KS_STEP(p, inc);
                    v = p + p - 1.0f;
                    KS_BLEP(v, -1.0f, p, inc, rinc);
                    KS_EMIT(i, v);
                }
            } else if (wave == 1) {                     /* square */
                /* Both edges look alike in the half-cycle phase q, so one
                 * signed residual serves the rising and the falling edge.
                 * (Two full KS_BLEPs cost half again as many cycles.) */
                for (i = 0; i < SH_FRAMES; i++) {
                    float v, q, sg;
                    KS_STEP(p, inc);
                    if (p < 0.5f) { q = p;        sg =  1.0f; }
                    else          { q = p - 0.5f; sg = -1.0f; }
                    v = sg;
                    if (q < inc) {                      /* just past an edge */
                        float x_ = q * rinc;
                        v += sg * (x_ + x_ - x_ * x_ - 1.0f);
                    }
                    if (q > 0.5f - inc) {               /* just before the next */
                        float x_ = (q - 0.5f) * rinc;
                        v -= sg * (x_ * x_ + x_ + x_ + 1.0f);
                    }
                    KS_EMIT(i, v);
                }
            } else if (wave == 2) {                     /* triangle */
                for (i = 0; i < SH_FRAMES; i++) {
                    float v;
                    KS_STEP(p, inc);
                    v = p - 0.5f;
                    if (v < 0.0f) v = -v;
                    v = 4.0f * v - 1.0f;
                    KS_EMIT(i, v);
                }
            } else {                                    /* sine */
                for (i = 0; i < SH_FRAMES; i++) {
                    float v;
                    KS_STEP(p, inc);
                    KS_SIN01(v, p);
                    KS_EMIT(i, v);
                }
            }
        } else {
            p += inc * (float)SH_FRAMES;
            p -= (float)(int)p;
        }

        os->ph = p;
        os->g  = tg;   /* exactly the target: the ramp must not drift */
    }
}
