/* generated by tools-local/gen_tables.py; do not edit. */
#ifndef KS_TABLES_H
#define KS_TABLES_H

/* word offsets into KS_TAB (float32 words, const_blob) */
#define KS_TAB_INC      0   /* 128 words */
#define KS_TAB_RINC   128   /* 128 words */
#define KS_TAB_SEMI   256   /* 49 words */
#define KS_TAB_ENV    305   /* 101 words */
#define KS_TAB_LFO    406   /* 101 words */
#define KS_TAB_GLD    507   /* 101 words */
#define KS_TAB_WORDS  608

#define KS_N_NOTES   128
#define KS_N_SEMI    49
#define KS_N_STEPS   101

#endif /* KS_TABLES_H */
