/* generated by tools-local/gen_tables.py from manifest.json;
 * do not edit. Knob ranges for the desktop harness. */
#ifndef KS_MANIFEST_H
#define KS_MANIFEST_H

#define KS_STATE_BYTES_MANIFEST 84
#define KS_NUM_KNOBS 12
static const struct { const char *name; int max; int def; int vol; } KS_KNOBS[KS_NUM_KNOBS] = {
    { "Key", 1000, 0, 0 },
    { "Level", 100, 80, 1 },
    { "Wave1", 3, 0, 0 },
    { "Wave2", 4, 1, 0 },
    { "Pitch", 48, 24, 0 },
    { "Dtune", 100, 12, 0 },
    { "Mix", 100, 50, 0 },
    { "Glide", 100, 0, 0 },
    { "Atk", 100, 5, 0 },
    { "Rel", 100, 30, 0 },
    { "LFO", 100, 50, 0 },
    { "Rate", 100, 60, 0 },
};

#endif /* KS_MANIFEST_H */
